-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 17:01:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = '';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8mb4;
USE `blog`;

-- -----------------------------------------------------
-- Table `blog`.`blog_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`blog_user`;

CREATE TABLE IF NOT EXISTS `blog`.`blog_user`
(
    `user_id`    INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `username`   VARCHAR(40)      NOT NULL COMMENT '用户名',
    `password`   VARCHAR(255)     NOT NULL COMMENT '密码',
    `role`       TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '角色',
    `created_at` INT              NOT NULL COMMENT '注册时间',
    `created_ip` VARCHAR(15)      NOT NULL COMMENT '注册IP',
    PRIMARY KEY (`user_id`),
    UNIQUE INDEX `username_UNIQUE` (`username` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`blog_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`blog_category`;

CREATE TABLE IF NOT EXISTS `blog`.`blog_category`
(
    `category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(20)  NOT NULL COMMENT '分类名称',
    `status`      TINYINT      NOT NULL DEFAULT 1 COMMENT '状态',
    `posts`       INT          NOT NULL DEFAULT 0 COMMENT '文章数',
    `user_id`     INT UNSIGNED NOT NULL,
    PRIMARY KEY (`category_id`),
    INDEX `fk_blog_category_blog_user1_idx` (`user_id` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`blog_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`blog_post`;

CREATE TABLE IF NOT EXISTS `blog`.`blog_post`
(
    `post_id`       INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title`         VARCHAR(100) NOT NULL COMMENT '标题',
    `content`       TEXT         NOT NULL COMMENT '内容',
    `status`        TINYINT      NOT NULL DEFAULT 1 COMMENT '状态',
    `top`           TINYINT      NOT NULL DEFAULT 0 COMMENT '置顶标记',
    `sort`          INT          NOT NULL DEFAULT 0 COMMENT '排序',
    `praise_count`  INT          NOT NULL DEFAULT 0,
    `comment_count` INT          NOT NULL DEFAULT 0,
    `created_at`    INT UNSIGNED NOT NULL COMMENT '创建时间',
    `updated_at`    INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
    `category_id`   INT UNSIGNED NOT NULL,
    `user_id`       INT UNSIGNED NOT NULL,
    PRIMARY KEY (`post_id`),
    INDEX `fk_blog_post_blog_category_idx` (`category_id` ASC),
    INDEX `fk_blog_post_blog_user1_idx` (`user_id` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`blog_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`blog_comment`;

CREATE TABLE IF NOT EXISTS `blog`.`blog_comment`
(
    `comment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `content`    VARCHAR(140) NOT NULL COMMENT '评论内容',
    `created_at` INT          NOT NULL COMMENT '评论时间',
    `post_id`    INT UNSIGNED NOT NULL,
    `user_id`    INT UNSIGNED NOT NULL,
    PRIMARY KEY (`comment_id`),
    INDEX `fk_blog_comment_blog_post1_idx` (`post_id` ASC),
    INDEX `fk_blog_comment_blog_user1_idx` (`user_id` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`blog_praise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`blog_praise`;

CREATE TABLE IF NOT EXISTS `blog`.`blog_praise`
(
    `post_id`    INT UNSIGNED NOT NULL,
    `user_id`    INT UNSIGNED NOT NULL,
    `created_at` INT          NOT NULL,
    PRIMARY KEY (`post_id`, `user_id`),
    INDEX `fk_table1_blog_user1_idx` (`user_id` ASC)
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
